### ISSUE TITLE
Error opening terminal: rxvt-unicode-256color

### ISSUE THREAD

**Issue by przmv** [snapcrafters/mutt#2]
I'm using Debian stretch as my host OS.

I've just installed `mutt`:

```
$ sudo snap install mutt
```

When I try to open it, I get the following error message:

```
$ which mutt
/snap/bin/mutt

$ mutt
Error opening terminal: rxvt-unicode-256color.
```

It starts OK when I run `mutt` as the following:

```
$ TERM=xterm mutt
```

However, I'd like to have a way to use the actual terminfo.

**Comment by popey** [comment]
Thanks for the bug report. I did a little research. It looks like the terminfo file could be loaded if placed in the home directory of the mutt snap which is `~/snap/mutt/common`. I guess this from this blog post. http://alemani.com/urxvt-unknown-terminal-type-with-ssh/

Worth a try?

**Comment by przmv** [comment]
On Wed, May 15, 2019 at 03:26:05AM -0700, Alan Pope wrote:
> Thanks for the bug report. I did a little research. It looks like the terminfo file could be loaded if placed in the home directory of the mutt snap which is `~/snap/mutt/common`. I guess this from this blog post. http://alemani.com/urxvt-unknown-terminal-type-with-ssh/
> 
> Worth a try?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/snapcrafters/mutt/issues/2#issuecomment-492598275

I've tried to symlink `/usr/share/terminfo` to
`$HOME/snap/mutt/{common,current}/.terminfo` but had no luck running
`mutt` from my terminal emulator (`rxvt-unicode-256color`).

I also tried to `strace /snap/bin/mutt` but there were no mentions of
any terminfo lookups.

**Comment by przmv** [comment]
Oh, I've just realized that symlinking won't work because the snap has no access to the host filesystem. When I _copied_ the `/usr/share/terminfo` directory `mutt` no longer complains on my terminal.

**Comment by popey** [comment]
Ok, good to know. Do we need to bundle the terminfo files inside the snap, I wonder?

**Comment by jnsgruk** [comment]
Fixed in https://github.com/snapcrafters/mutt/commit/f5754bb60ccba4dcc168a5b0f5a4917e96dc3115
