### ISSUE TITLE
Unable to save any messages, mutt_dotlock missing

### ISSUE THREAD

**Issue by kikoreis** [snapcrafters/mutt#3]
Fresh install of latest version:

    mutt                  1-12-1-rel                  147   stable    snapcrafters   -

Visit any existing folder and I get a warning to stderr, but the mbox does open:

    Reading /home/kiko/devel/mail/sent-mail...sh: 1: /bin/mutt_dotlock: not found

Try to save any message into a new file, and I get this failure on stderr:

    Reading /home/kiko/devel/mail/sent-mail...sh: 1: /bin/mutt_dotlock: not found
    Copying to /home/kiko/foo.mbox...sh: 1: /bin/mutt_dotlock: not found

**Comment by popey** [comment]
@kikoreis Thanks for the bug report. Shortly (modulo launchpad builders) a new build should exist in the edge channel. Please test and feedback if that fixes the issue.

**Comment by kikoreis** [comment]
I just checked and no update came out on edge this week -- I installed
the Oct 10th update and the failure is the same:

    Copying to /home/kiko/snap/mutt/common/Mail/foo...sh: 1:
    /bin/mutt_dotlock: not found
    Couldn't lock /home/kiko/snap/mutt/common/Mail/foo?

Also, when I start up mutt, I get the following two warnings:

    /etc/Muttrc: Permission denied
                                  Press any key to continue...

and

    /var/mail/kiko: No such file or directory (errno = 2)

I think I understand why they happen, but wanted to make sure they are
captured somewhere.

On Mon, Oct 28, 2019 at 11:32:56PM -0700, Alan Pope wrote:
> @kikoreis Thanks for the bug report. Shortly (modulo launchpad builders) a new build should exist in the edge channel. Please test and feedback if that fixes the issue.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/snapcrafters/mutt/issues/3#issuecomment-547277338

-- 
Christian Robottom Reis | [+55 16] 3376 0125   | http://async.com.br/~kiko
                        | [+55 16] 9 9112 6430 | http://launchpad.net/~kiko
