### ISSUE TITLE
Please update the version of mutt in the Snap Store

### ISSUE THREAD

**Issue by duckunix** [snapcrafters/mutt#6]
Mutt 1.14.7 was released today, but the version in the store has not been updated since last year.  I did pull this repo, and ran snapcraft against it, and it built nicely and works.

**Comment by popey** [comment]
Thanks for filing this issue. Apologies it took too long to get to. I've updated the release, and updated our internal job which notifies when these snaps are outdated. So we shouldn't be outdated again.
